version: '2'
services:
  read_stream:
    build:
      context: .
      dockerfile: Dockerfile-read-stream
    depends_on:
     - rabbitmq
    volumes:
     - .:/www
    tty: true
    env_file: .env.local

  read_message_queue:
    build:
      context: .
      dockerfile: Dockerfile-read-message-queue
    depends_on:
     - rabbitmq
     - mysql
    volumes:
     - .:/www
    tty: true
    env_file: .env.local

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
     - "15672:15672"
     - "5672:5672"
    env_file: .env.local

  mysql:
    image: "mysql"
    ports:
     - "3306:3306"
    env_file: .env.local