FROM php:7.1-cli
ADD . /www
WORKDIR /www

RUN apt-get update
RUN apt-get install -y mysql-client

RUN docker-php-ext-install bcmath \
    pdo_mysql

RUN chmod +x /www/bin/read-message-queue.sh

CMD ./bin/read-message-queue.sh